### ISSUE TITLE
Jdetects easily bypassable

### ISSUE THREAD

**Issue by mmtftr** [zswang/jdetects#2]
If this is something you'd like to fix or just add to documentation. 

Backstory: A website using jdetects was stopping me from changing and inspecting its content so I went to work to find which library it uses and how I can bypass it.

It is quite easy to bypass jdetects. Just create a script to be injected with the following content:
```js
Object.defineProperty(window, "jdetects", {
    value: 'jdetects = bypassed',
    writable: false
});
``` 
and this hinders any other script from accessing jdetects. Of course this can easily bypassed by changing the name of the property that contains jdetects. 
Just wanted to let you know about this so you can maybe add it to the README.MD file so people know how to bypass it if/when they need to.

**Comment by zswang** [comment]
Do not use global variables

```js
(function () {
  let jdetects  = require('jdetects')
  // TODO
})()
```

Thanks.
