### ISSUE TITLE
jdetcts does not work in Google Chrome Canary any more.

### ISSUE THREAD

**Issue by aki2014** [zswang/jdetects#3]
I am afraid jdetcts will not work in Google Chorme in the near future.
Google Chrome Canary shows the problem. Jdetects does not detect if console is open.

My bisect points me to:
https://chromium-review.googlesource.com/c/chromium/src/+/846239
https://chromium.googlesource.com/chromium/src/+/f671d5a01135eb084bbec171d536cb5d1248e124
is possibly the cause.

This commit was added on Decmeber 29th, about 3 days ago.

I love your javascript. Please update your great project.

Thank you in advance.

**Comment by agustinhaller** [comment]
Can confirm it's no longer working in Chrome 65. @zswang how can I help solve this?

**Comment by zswang** [comment]
Have a try.

Thank @aki2014 & @agustinhaller

**Comment by agustinhaller** [comment]
Yup, it's working again. Thanks @zswang!! Feel free to close this issue.

**Comment by EntrepreneurVE** [comment]
why not work properly in mozilla firefox, can you fix it bro?

**Comment by balotz** [comment]
Not working in Chrome 73 (canary).
